# Site settings
title: Avon Kayit AYCA DUMER | AA
description: "Avon'un en kolay kayit sistemi"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo_avon.jpg

# Hero
hero: 
    hero_img: subat_katalog.jpg
    hero_title: Avon Kayit AYCA DUMER
    hero_description: Avon'un en kolay kayit sistemi

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +90 535 305 90 32
    emergency: +90 535 305 90 32
    email: ayca@gmail.com
    Address: Tarsus 

# Calisma Saatleri
monday-friday: 9:00 – 22:00
saturday: 10:00 – 21:00
sunday: 10:00 – 22:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Tarsus
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 AYCA DUMER AVON - Tum haklari saklidir

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
